config/routes.rb
Tabatas::Application.routes.draw do
  
  root :to => "exercises#program"
  get "index.html", :to => "exercises#program"
  
  get "exercises/program"
  get 'tags/:tag', to: 'exercises#index', as: :tag
  resources :exercises
  
  get "pages/index"

  match "/auth/:provider/callback" => "sessions#create"
  match 'auth/failure', to: redirect('/')
  match "/signout" => "sessions#destroy", :as => :signout

  

   match ':controller(/:action(/:id))(.:format)'
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  attr_accessible :description, :name, :tag_list, :today , :image, :remote_image_url, :image_cache
  has_many :taggings
  has_many :tags, through: :taggings
  
  mount_uploader :image, ImageUploader

  scope :today, where(:today => true)
  
  def self.tagged_with(name)
    Tag.find_by_name!(name).exercises
  end
  
  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id")
  end
  
  def tag_list
    tags.map(&:name).join(", ")
  end
  
  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end        

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_many :taggings
  has_many :exercises, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :exercise
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :name, :provider, :uid

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
    
  def pages
    render('pages/index') 
    # redirect_to(:action => 'other_hello')
  end
  
  def index
    render('pages/index') 
    # redirect_to(:action => 'other_hello')
  end

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  # GET /exercises
  # GET /exercises.json
  def index
    if params[:tag]
      @exercises = Exercise.tagged_with(params[:tag])
      @title  = params[:tag].to_s

      
    else
      @title = "Exercises"      
      @exercises = Exercise.all
    end    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exercises }
    end
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
    @exercise = Exercise.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exercise }
    end
  end

  # GET /exercises/new
  # GET /exercises/new.json
  def new
    @exercise = Exercise.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exercise }
    end
  end

  # GET /exercises/1/edit
  def edit
    @exercise = Exercise.find(params[:id])
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(params[:exercise])

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise suggestion successfully submitted.' }
        format.json { render json: @exercise, status: :created, location: @exercise }
      else
        format.html { render action: "new" }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exercises/1
  # PUT /exercises/1.json
  def update
    @exercise = Exercise.find(params[:id])

    respond_to do |format|
      if @exercise.update_attributes(params[:exercise])
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def program
        
        @today = Time.now.to_s(:dateheader) 
          
        @exercises = Exercise.all
        
        @tabata1 = @exercises[1]
        @tabata2 = @exercises[3]


        # @dothese = Exercise.where(:today => true)
        @dothese = Exercise.today
          if @dothese.length > 1
            @mytabata1 = @dothese[0]
            @mytabata2 = @dothese[1]
          else
            @mytabata1 = @tabata1
            @mytabata2 = @tabata2

          end
        
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @exercises }
      end
  end
  
  
  

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  
  def delete
      @exercise = Exercise.find(params[:id])
   end


  
  
  def destroy
    @exercise = Exercise.find(params[:id])
    @exercise.destroy

    respond_to do |format|
      format.html { redirect_to exercises_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  
  
  
  
  def index
      
    @today = Time.now.to_s(:dateheader) 
      
    render('pages/index')
    
    # @tabatas = Exercise.find_by(:today)
     
  end
      
  
 
  
  def text_helpers
  end
  
  def escape_output
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end
  
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  
  
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/exercises/_clock.html.haml
%h5
  = link_to 'Tabata timer', 'http://www.tabatatimer.com/', :class => 'btn btn-inverse btn-large'

app/views/exercises/_form.html.haml
= form_for @exercise, :html => {:multipart => true} do |f|
  - if @exercise.errors.any?
    #error_explanation
      %h2= "#{pluralize(@exercise.errors.count, "error")} prohibited this exercise from being saved:"
      %ul
        - @exercise.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name, :class => "span5"
  .field
    = f.label :tag_list, "Tags"
    = f.text_field :tag_list, :class => "input-large" , :placeholder => "Separate tags by comma.", :class => "span5"
  .field
    = f.label :description
    = f.text_area :description, :placeholder => "Simple format support <p>,<br>,<b>, etc."  , :class => "span5"

  %fieldset
    %h5 Image
    .well.span4
      = f.file_field :image, :placeholder => "Select file ...", :class => "span4"
      = f.hidden_field :image_cache
      = f.label :remote_image_url, "or Image URL"
      = f.text_field :remote_image_url, :placeholder => "http://...", :class => "span4"

  .field
    = f.check_box(:today)
    = "Today"
    %br
    %br

  
  .actions
    = f.submit 'Save',:class => "btn btn-inverse"

app/views/exercises/_todays_selection.html.haml
.field
  = check_box_tag(:today)

app/views/exercises/_todays_tabatas.html.haml
.span9
  %h2 #{ link_to @mytabata1.name, @mytabata1, :class => 'exercise'}
  = image_tag @mytabata1.image_url.to_s
 


  %h2 #{ link_to @mytabata2.name, @mytabata2, :class => 'exercise'}
  = image_tag @mytabata2.image_url.to_s
 

    
    

app/views/exercises/_twitter_widget.html.haml
<a class="twitter-timeline" href="https://twitter.com/search?q=%23tabatas+OR++%23twotabatas+OR+%232tabatas" data-widget-id="285599145488683009">Tweets about "#tabatas OR #twotabatas OR #2tabatas"</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/exercises/_two_tabatas.html.haml
%hr
.row

  .span7
   
    = render 'todays_tabatas'
 
  .span1
    
  .span4
    = render 'twitter_widget'
		

app/views/exercises/delete.html.haml
%h2
  = "Delete Exercise :"
  =  @exercise.name

= form_for(:exercise ,:url => {:action => 'destroy', :id => @exercise.id}) do |f|

  %legend
    This will permanently delete this exercise

   

  %form-buttons
    = submit_tag("Delete Exercise", :class => "btn btn-danger")

app/views/exercises/edit.html.haml
%h1 Editing exercise

= render 'form'

%hr
= link_to 'delete', @exercise, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'edit'
\|
= link_to 'Show', @exercise
\|
= link_to 'Back', exercises_path

app/views/exercises/index.html.haml
.row
  .span6
    %h1  
      
      = @title
  .span6
   
    -# #tag_cloud
      -# -tag_cloud Exercise.tag_counts, %w[s m l] do |tag, css_class| 
        -# = link_to tag.name, tag_path(tag.name), class: css_class 


%table.table.table-hover
  %tr
    %th{:colspan => 2}
      = "Today"
    %th 
    %th
      = link_to '+', new_exercise_path, :class => 'controls'
    
      

  - @exercises.each do |exercise|
    %tr
      
      
      
      %td{:class => 'name'}
        - if exercise.today == true
          = " -"

      %td= link_to exercise.name , exercise, :class => 'name'
      %td= truncate(exercise.description, :length => 80, :omission => "...")
      %td= raw exercise.tags.map(&:name).map { |t| link_to t, tag_path(t), :class => 'btn' }.join(' ')
      -# %td=  link_to '/' , edit_exercise_path(exercise), :class => 'edit'
      -# %td= link_to 'X', delete_exercise_path(exercise), :class => 'edit'
      -# %td= link_to("X", {:action => 'delete', :id => exercise.id}, :class => 'edit')
      -# %td= link_to 'X', exercise, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'edit'

app/views/exercises/new.html.haml
%h1 Suggest a new exercise

= render 'form'

= link_to 'Back', exercises_path

app/views/exercises/program.html.haml
.row
  .span8 
    %h1  #{@today}
      
  .span4
    = render 'clock'
.row
  = render 'two_tabatas'

app/views/exercises/programtrials.html.haml
%h1  
  = @today
 
%h3
  
%hr

= form_for :exercise do |f|

  = f.label "Tabata 1"
  -# = f.select(:today, @exercises.collect {|s| [s.name, s.id]})
  = f.radio(:today,  @exercises.collect {|s| [s.name, s.id]}) 

  .actions
    = f.submit 'Save',:class => "btn btn-inverse"



    
-# - @exercises.each do |exercise|
  -# %ul
         
    -# %li= link_to exercise.name , exercise, :class => 'name'
     

app/views/exercises/show.html.haml
%p#notice= notice

%h1
  = @exercise.name

.row
  .span7 
    = simple_format @exercise.description
    = image_tag @exercise.image_url.to_s if @exercise.image?


  .span1
  .span4
    =  raw @exercise.tags.map(&:name).map { |t| link_to t, tag_path(t), :class => 'btn btn-large' }.join(' ')
    %hr
     
 
      
       
          
   

app/views/layouts/_footer.html.haml
.row
  .span12
    .footernotes
      %hr
      = "Don't have time to workout?  just do 2 "
      = link_to( 'tabatas ', 'http://en.wikipedia.org/wiki/High-intensity_interval_training#Tabata_method')
      ="today."

app/views/layouts/_navbar.html.haml
.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      -# =link_to '', :class => 'btn btn-navbar' "data-toggle = 'collapse', data-target = 'nav-collapse'"
      -#  %span.icon-bar
      -#  %span.icon-bar
      -#  %span.icon-bar
      
      %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      =link_to '2Tabatas ', '/', :class => 'brand'

      .nav-collapse
        %ul.nav
          %li
            = link_to 'Exercises', '/exercises'

        %ul.nav.pull-right.nav-pills
          %li
            - if current_user
              -# = "Signed in as"
              %a.btn.btn-inverse.dropdwon_toggle{"data-toggle" => "dropdown", "href" => "#"}
                = current_user.name.strip
              %ul.dropdown-menu
                %li.dropdown
                  = link_to "Sign out", signout_path

            - else
              %a.btn.btn-inverse.dropdwon_toggle{"data-toggle" => "dropdown", "href" => "#"}
                = "Sign in"
              %ul.dropdown-menu
                %li.dropdown
                  = link_to 'with Twitter', "/auth/twitter"
                -# %li.dropdown
                  -# = link_to "with Facebook", "/auth/facebook"

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
%head
  %title Tabatas 
  = javascript_include_tag "application" 
  = csrf_meta_tags 
  = stylesheet_link_tag   "application", :media => "all"

%body
  = render 'layouts/navbar'

  .container      
    = yield 

    = render 'layouts/footer'

app/views/pages/index.html.haml
%h1 
  = @today